[keyboard]
bindings = [
    { chars = "\u001B.", key = "Period", mods = "Command" },
    { chars = "\u001Bh", key = "H", mods = "Command" },
    { chars = "\u001Bj", key = "J", mods = "Command" },
    { chars = "\u001Bk", key = "K", mods = "Command" },
    { chars = "\u001Bl", key = "L", mods = "Command" },
    { chars = "\u001Bm", key = "M", mods = "Command" },
    { chars = "\u001Bs", key = "S", mods = "Command" },
    { chars = "\u001Bd", key = "D", mods = "Command" },
    { chars = "\u001Ba", key = "A", mods = "Command" },
    { chars = "\u001Br", key = "R", mods = "Command" },
    { chars = "\u001Be", key = "E", mods = "Command" },
    { action = "CreateNewWindow", key = "N", mods = "Command|Shift" },
    { action = "ClearLogNotice", key = "C", mods = "Command|Control" },
    { chars = "\u001b\u000c", key = "L", mods = "Command|Control" }, # Escape + Control + L
    { chars = "\u001b\u000b", key = "K", mods = "Command|Control" },  # Escape + Control + K
    { chars = "\u001b\u0008", key = "H", mods = "Command|Control" },  # Escape + Control + H
    { chars = "\u001b\u000a", key = "J", mods = "Command|Control" },  # Escape + Control + J
    { chars = "\u001B]", key = "RBracket", mods = "Command" },
    { chars = "\u001B[", key = "LBracket", mods = "Command" },
    { chars = "\u001Ba", key = "A", mods = "Alt" },
    { chars = "\u001Bb", key = "B", mods = "Alt" },
    { chars = "\u001Bc", key = "C", mods = "Alt" },
    { chars = "\u001Bd", key = "D", mods = "Alt" },
    { chars = "\u001Be", key = "E", mods = "Alt" },
    { chars = "\u001Bf", key = "F", mods = "Alt" },
    { chars = "\u001Bg", key = "G", mods = "Alt" },
    { chars = "\u001Bh", key = "H", mods = "Alt" },
    { chars = "\u001Bi", key = "I", mods = "Alt" },
    { chars = "\u001Bj", key = "J", mods = "Alt" },
    { chars = "\u001Bk", key = "K", mods = "Alt" },
    { chars = "\u001Bl", key = "L", mods = "Alt" },
    { chars = "\u001Bm", key = "M", mods = "Alt" },
    { chars = "\u001Bn", key = "N", mods = "Alt" },
    { chars = "\u001Bo", key = "O", mods = "Alt" },
    { chars = "\u001Bp", key = "P", mods = "Alt" },
    { chars = "\u001Bq", key = "Q", mods = "Alt" },
    { chars = "\u001Br", key = "R", mods = "Alt" },
    { chars = "\u001Bs", key = "S", mods = "Alt" },
    { chars = "\u001Bt", key = "T", mods = "Alt" },
    { chars = "\u001Bu", key = "U", mods = "Alt" },
    { chars = "\u001Bv", key = "V", mods = "Alt" },
    { chars = "\u001Bw", key = "W", mods = "Alt" },
    { chars = "\u001Bx", key = "X", mods = "Alt" },
    { chars = "\u001By", key = "Y", mods = "Alt" },
    # { chars = "\u001By", key = "Y", mods = "Alt" }
    { chars = "\u001Bz", key = "Z", mods = "Alt" },
    { chars = "\u001B;", key = "Semicolon", mods = "Alt" },
    { chars = "\u001B,", key = "Comma", mods = "Alt" },
    { chars = "\u001B]", key = "RBracket", mods = "Alt" },
    { chars = "\u001B[", key = "LBracket", mods = "Alt" },
    { chars = "\u001B.", key = "Period", mods = "Alt" },
    { chars = "\u001B:", key = "Semicolon", mods = "Alt|Shift" },
    { chars = "\u001B>", key = "Period", mods = "Alt|Shift" },
    { chars = "\u001B<", key = "Comma", mods = "Alt|Shift" },
    { chars = "\u001B}", key = "RBracket", mods = "Alt|Shift" },
    { chars = "\u001B{", key = "LBracket", mods = "Alt|Shift" },
    { chars = "\u001B}", key = "RBracket", mods = "Command|Shift" },
    { chars = "\u001B{", key = "LBracket", mods = "Command|Shift" },
    { chars = "\u001B\u007F", key = "Back", mods = "Command" },
    { chars = "\u001Bt", key = "T", mods = "Alt" },
    { chars = "!", key = "Key1", mods = "Command" },
    { chars = "@", key = "Key2", mods = "Command" },
    { chars = "#", key = "Key3", mods = "Command" },
    { chars = "$", key = "Key4", mods = "Command" },
    { chars = "%", key = "Key5", mods = "Command" },
    { chars = "^", key = "Key6", mods = "Command" },
    { chars = "&", key = "Key7", mods = "Command" },
    { chars = "*", key = "Key8", mods = "Command" },
    { chars = "(", key = "Key9", mods = "Command" },
    { chars = "\u001Bt", key = "T", mods = "Command" },
    { chars = "\u001Bp", key = "P", mods = "Command" },
    { chars = "\u001Bn", key = "N", mods = "Command" },
    { chars = "\u001Bf", key = "F", mods = "Command" },
    { chars = "\u001Bb", key = "B", mods = "Command" },
    { chars = "\u001Bx", key = "X", mods = "Command" },
    { chars = "\u001Bw", key = "W", mods = "Command" },
    { chars = "\u001B!", key = "Key1", mods = "Alt|Shift" },
    { chars = "\u001B!", key = "Key1", mods = "Command|Shift" },
    { chars = "\u001B%", key = "Key5", mods = "Alt|Shift" },
    { chars = "\u001B%", key = "Key5", mods = "Command|Shift" },
    { chars = "\u001B&", key = "Key7", mods = "Alt|Shift" },
    { chars = "\u001B&", key = "Key7", mods = "Command|Shift" },
    { chars = "\u001B/", key = "Slash", mods = "Command" },
    { chars = "\u001B\r", key = "Return", mods = "Command" },
    { chars = "\u001B>", key = "Period", mods = "Command|Shift" },
    { chars = "\u001B<", key = "Comma", mods = "Command|Shift" },
    { chars = "\u001B;", key = "Semicolon", mods = "Command" },
    { chars = "\u001B,", key = "Comma", mods = "Command" },
    { chars = "\u001B\\", key = "Backslash", mods = "Command" },
    { chars = "\u0000", key = "Space", mods = "Control" },
    { chars = "\u001B1", key = "1", mods = "Command" },
    { chars = "\u001B2", key = "2", mods = "Command" },
    { chars = "\u001B3", key = "3", mods = "Command" },
    { chars = "\u001B4", key = "4", mods = "Command" },
    { chars = "\u001B5", key = "5", mods = "Command" },
    { chars = "\u001B6", key = "6", mods = "Command" },
    { chars = "\u001B7", key = "7", mods = "Command" },
    { chars = "\u001B8", key = "8", mods = "Command" },
    { chars = "\u001B9", key = "9", mods = "Command" },
    # Tmux toggle last window
    { chars = "\u001Bo", key = "o", mods = "Command" },
    # Tmux toggle last session
    { chars = "\u001BO", key = "o", mods = "Command|Shift" },
    # Tmux toggle last session
    { chars = "\u001BO", key = "o", mods = "Command|Shift" },
]
