require("reverseila/set")
require("reverseila/remap")
require("reverseila/hook")
require("reverseila/packer")
require("reverseila/lsp")
-- require("reverseila/utils/statusline")
-- vim.cmd("set bg=light")
