-- local ok = pcall(require, 'nvim-treesitter')
-- if not ok then
--   return
-- end
--
-- require('nvim-treesitter.configs').setup {
--   highlight = { enable = true, },
--
--   indent = { enable = false, },
--
--   ensure_installed = { 'c', 'cpp', 'lua', 'python', 'comment', },
--
--   endwise = { enable = true, },
--
--   autotag = {
--     enable = true,
--     filetypes = { 'html', 'htmldjango', 'javascript', 'typescript',
--     'javascriptreact', 'typescriptreact', 'svelte', 'vue', 'tsx', 'jsx',
--     'rescript', 'xml', 'php', 'markdown', 'astro', 'glimmer', 'handlebars',
--     'hbs' },
--     skip_tags = { 'area', 'base', 'br', 'col', 'command', 'embed', 'hr', 'img',
--     'slot', 'input', 'keygen', 'link', 'meta', 'param', 'source', 'track',
--     'wbr', 'menuitem', 'option' },
--   },
--
--   context_commentstring = { enable = true, },
-- }
