#!/bin/sh
#source: tpope (https://tbaggery.com/2011/08/08/effortless-ctags-with-git.html)
set -e
[ "$(uname -s)" = "Darwin" ] && PATH="$(brew --prefix)/bin:$PATH"
trap 'rm -f "$$.tags"' EXIT INT TERM
git ls-files | ctags --tag-relative -L - -f"$$.tags" --languages=C++,C
mv "$$.tags" "tags"
